name: 'Setup'
description: 'Setup for Otter Library'

inputs:
  enable-build-cache:
    description: 'Enable Cache'
    deprecationMessage: 'The build cache is now handle only by Nx Cloud, this option will not have any effect anymore'
    required: false
    default: 'false'
  cache-build-identifier:
    description: 'Custom identifier to build cache key'
    deprecationMessage: 'The build cache is now handle only by Nx Cloud, this option will not have any effect anymore'
    required: false
    default: 'global'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          .yarn/cache
          .yarn/unplugged
          .pnp.cjs
          .pnp.loader.mjs
        key: ${{ runner.os }}-deps-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-deps
          ${{ runner.os }}
    - name: Install
      shell: bash
      run: yarn install
