name: Upload Build Output
description: Upload a github artifact containing all `dist` outputs

runs:
  using: 'composite'
  steps:
    - run: zip -q -r dist.zip . -i "apps/*/dist/*" "packages/*/dist/*" -x "*/node_modules/*" ".cache/*"
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist.zip
    - run: rm -f dist.zip
      shell: bash
