name: Main CI

concurrency:
  group: ci-${{ github.ref }}-main
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./tools/github-actions/setup
        with:
          enable-build-cache: 'true'
      - uses: ./.github/actions/setup-java
        with:
          install-jdk: 'true'
      - run: yarn build:swagger-gen
      - run: yarn build
      - uses: ./tools/github-actions/upload-build-output
  version:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      nextVersionTag: ${{ steps.newVersion.outputs.nextVersionTag }}
      isPreRelease: ${{ contains( steps.newVersion.outputs.nextVersionTag, '-' ) || github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./tools/github-actions/setup
      - name: New Version
        id: newVersion
        uses: ./tools/github-actions/new-version
        with:
          defaultBranch: main
          defaultBranchPrereleaseName: alpha
      - name: Create release
        if: github.event_name != 'pull_request'
        run: gh release create v${{ steps.newVersion.outputs.nextVersionTag }} --generate-notes ${{ contains( steps.newVersion.outputs.nextVersionTag, '-' ) && '--prerelease' || '' }} --target ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  checks:
    uses: ./.github/workflows/code-check.yml
    with:
      affected: ${{ github.event_name == 'pull_request' }}
  publish-packages:
    uses: ./.github/workflows/publish.yml
    permissions:
      packages: write
      contents: read
    secrets: inherit
    needs: [version, build, checks]
    with:
      version: ${{ needs.version.outputs.nextVersionTag }}
      prerelease: ${{ needs.version.outputs.isPreRelease == 'true' }}
  cascading:
    runs-on: ubuntu-latest
    needs: [version, build, checks]
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./tools/github-actions/cascading
