name: Check external links
on:
  workflow_dispatch:
  schedule:
    - cron: "20 4 * * 1"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        base-branch: 'main'
        config-file: '.github/markdown-external-links.config.json'
