name: Pull Request Label

on:
  workflow_run:
    workflows: ['Main CI']

jobs:
  setup-label:
    if: ${{ github.event.workflow_run.event == 'pull_request' }}
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./tools/github-actions/setup
      - name: Determine labels
        run: |
          LABELS="$(yarn pr-labels --target="${{ github.base_ref || github.ref_name }}")"
          echo "LABELS=$LABELS" >> $GITHUB_ENV
      - uses: actions/github-script@v6
        if: env.LABELS != '[]'
        continue-on-error: true
        with:
          script: |
            const [owner, repo] = '${{ github.repository }}'.split('/');
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: context.issue.number,
              labels: ${{ env.LABELS }}
            })
