name: Pull Request Label

on: pull_request

jobs:
  setup-label:
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup
        uses: ./tools/github-actions/setup
      - run: |
          LABELS="$(yarn pr-labels "$(git log -1 --pretty=%B || echo '')")"
          echo "LABELS=$LABELS" >> $GITHUB_ENV
      - uses: actions/github-script@v6
        if: env.LABELS != '[]'
        continue-on-error: true
        with:
          script: |
            const [owner, repo] = '${{ github.repository }}'.split('/');
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: context.issue.number,
              labels: ${{ env.LABELS }}
            })
