name: Publish Packages

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
        description: Version of the artifact to publish
      prerelease:
        type: boolean
        default: false
        required: false
        description: Version of the artifact to publish
    secrets:
      AZURE_VSC_EXT_TOKEN:
        required: false
        description: Token to publish Visual Studio Code extension
      NPM_TOKEN:
        required: false
        description: PAT to publish on npmjs.org
      AZURE_AUTH_TOKEN:
        required: false
        description: Token of the user publishing on Azure Feeds for PR Artifacts
      AZURE_USERNAME:
        required: false
        description: Name of the user publishing on Azure Feeds for PR Artifacts
      AZURE_EMAIL:
        required: false
        description: Email of the user publishing on Azure Feeds for PR Artifacts

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: ${{github.event_name == 'pull_request' && 'development' || 'production'}}
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/download-build-output
      - uses: ./.github/actions/setup
        with:
          enable-build-cache: ${{ github.event_name == 'pull_request' }}
      - run: yarn set:version ${{ inputs.version }}
      - name: Get tag name
        id: get-npm-tag
        uses: ./.github/actions/get-npm-tag
        with:
          is-prerelease: ${{ inputs.prerelease }}
          version: ${{ inputs.version }}
      - name: Publish
        continue-on-error: ${{ github.event_name == 'pull_request' }}
        run: yarn run publish --tag=${{ github.event_name == 'pull_request' && 'pr' || steps.get-npm-tag.outputs.tag }} ${{ github.event_name == 'pull_request' && '--userconfig=./.npmrc.pr' || ''}} --always-auth=true
        env:
          GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          AZURE_AUTH_TOKEN: ${{ secrets.AZURE_AUTH_TOKEN }}
          AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
          AZURE_EMAIL: ${{ secrets.AZURE_EMAIL }}
      - name: Publish Extensions
        if: '!inputs.prerelease'
        run: yarn run publish:extensions
        env:
          VSCE_PAT: ${{ secrets.AZURE_VSC_EXT_TOKEN }}
          CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CHROME_EXT_ID: ${{ secrets.CHROME_EXT_ID }}
          CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
