name: Test publish

on:
  workflow_call:
    secrets:
      NX_CLOUD_ACCESS_TOKEN:
        required: false
        description: Token to use Nx Cloud token

jobs:
  test-publish:
    runs-on: ubuntu-20.04
    env:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./tools/github-actions/download-build-output
      - uses: ./tools/github-actions/setup
      - uses: ./.github/actions/setup-java
        with:
          install-jdk: 'true'
      - name: Get current month to build the cache key
        run: echo "currentMonth=$(date +'%Y-%m')" >> $GITHUB_ENV
        shell: bash
      - name: Cache test-app yarn
        uses: actions/cache@v3
        with:
          path: |
            .cache/test-app
            !.cache/test-app/v6/npm-@ama-sdk*
            !.cache/test-app/v6/npm-@ama-terasu*
            !.cache/test-app/v6/npm-@o3r*
          key: ${{ runner.os }}-test-app-${{ env.currentMonth }}
      - name: Test
        run: yarn test-int
      - name: Prepare for publish generated app
        if: failure()
        run: zip -r test-app.zip ../test-app -x "../test-app/node_modules/*"
      - name: Publish generated app
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-app
          path: test-app.zip
