name: Test publish

on:
  workflow_call:
    secrets:
      NX_CLOUD_ACCESS_TOKEN:
        required: false
        description: Token to use Nx Cloud token

jobs:
  test-publish:
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./tools/github-actions/download-build-output
      - uses: ./tools/github-actions/setup
      - uses: ./.github/actions/setup-java
        with:
          install-jdk: 'true'
      - name: Get current month to build the cache key
        run: echo "currentMonth=$(date +'%Y-%m')" >> $GITHUB_ENV
        shell: bash
      - name: Cache test-app yarn
        uses: actions/cache@v3
        with:
          path: |
            .cache/test-app
            !.cache/test-app/@ama-sdk*
            !.cache/test-app/@ama-terasu*
            !.cache/test-app/@o3r*
          key: ${{ runner.os }}-test-app-yarn3-${{ env.currentMonth }}
      - name: Cache test-sdk yarn
        uses: actions/cache@v3
        with:
          path: |
            .cache/test-sdk
            !.cache/test-sdk/@ama-sdk*
            !.cache/test-sdk/@ama-terasu*
            !.cache/test-sdk/@o3r*
          key: ${{ runner.os }}-test-sdk-yarn3-${{ env.currentMonth }}
      - name: Setup verdaccio once for all tests
        run: yarn verdaccio:start && yarn verdaccio:publish
      - name: Test
        run: yarn test-int
      - name: Stop verdaccio
        if: always()
        run: yarn verdaccio:stop
      - name: Prepare for publish generated app
        if: failure()
        run: zip -r it-tests.zip ../it-tests -x "../it-tests/*/.cache"
      - name: Publish generated tests environment
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: it-tests
          path: it-tests.zip
